version: "3.9"

services:
  django:
    ports:
      - "8000:8000"
    volumes:
      - "./backend/:/code"
    env_file:
      - ./backend/.env
    restart: always
    build:
      dockerfile: django.Dockerfile
    command: python api/manage.py runserver 0.0.0.0:8000
