version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: fastapi.Dockerfile
    image: fastapi
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - FASTPI_DEBUG=true
      - FASTPI_SECRET=supersecret
      - FASTPI_TITLE=FastAPI
      - FASTPI_VERSION=3.9
      - USER=${CURRENT_UID}
    restart: always
